# Generated by Django 4.0.6 on 2022-10-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_post_options_about_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
